# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.1.0
maven_group = io.github.moehreag
archives_base_name = soundfix

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.8.9
feather_build = 1
loader_version = 0.18.4

osl_version = 0.17.2
legacy_lwjgl3 = 1.2.11+1.8.9
