# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.0
maven_group = io.github.moehreag
archives_base_name = soundfix

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.16.1
yarn_build = 21
loader_version = 0.16.10

fapi = 0.18.0+build.387-1.16.1

